"""B3 Research Protocol Freezer - Freeze immutable research protocol snapshot."""
from __future__ import annotations

import hashlib
import json
from datetime import datetime

from backend.services.b3_protocol_types import (
    DataSnapshotManifest,
    OOSWindowSpec,
)
from backend.services.oos_window_rules import OOSWindowRuleRegistry
from backend.services.time_consistency_guard import TimeConsistencyGuard
from contracts.strategy import (
    BacktestUniverseSpec,
    ResearchProtocolSnapshot,
    StrategyDraft,
)


class ResearchProtocolFreezer:
    """
    Freeze immutable research protocol snapshot.
    
    Only freezes after all inputs validated:
    - Valid StrategyDraft
    - Valid BacktestUniverseSpec
    - Point-in-time membership ok or allowed degraded
    - Data snapshot hash exists
    - OOS window generated by registered rule
    - Gate criteria hash exists
    - Strategy config hash exists
    
    No LLM, no DB write, no Gate/report/promotion.
    """
    
    def freeze_protocol(
        self,
        strategy_draft: StrategyDraft,
        universe: BacktestUniverseSpec,
        data_snapshot: DataSnapshotManifest,
        oos_window: OOSWindowSpec,
        gate_criteria_hash: str,
        frozen_by: str,
        backtest_start: __import__("datetime").date,
    ) -> ResearchProtocolSnapshot:
        """
        Freeze research protocol snapshot.
        
        Args:
            strategy_draft: Valid B2 strategy draft
            universe: Valid backtest universe spec
            data_snapshot: Data snapshot manifest with hash
            oos_window: OOS window from registered rule
            gate_criteria_hash: Gate criteria hash
            frozen_by: Agent/user who froze protocol
            backtest_start: Backtest start date for time consistency check
        
        Returns:
            Immutable ResearchProtocolSnapshot
        
        Raises:
            ValueError: If any validation fails
        """
        # Validate strategy_config_hash
        if not strategy_draft.strategy_config_json or strategy_draft.strategy_config_json.strip() == "":
            raise ValueError("Missing strategy_config. Cannot freeze protocol.")
        
        strategy_config_hash = self._compute_config_hash(strategy_draft.strategy_config_json)
        
        # Validate data_snapshot_hash
        if not data_snapshot.data_snapshot_hash or data_snapshot.data_snapshot_hash.strip() == "":
            raise ValueError("Missing data_snapshot_hash. Cannot freeze protocol.")
        
        # Validate gate_criteria_hash
        if not gate_criteria_hash or gate_criteria_hash.strip() == "":
            raise ValueError("Missing gate_criteria_hash. Cannot freeze protocol.")
        
        # Validate OOS window rule is registered
        registry = OOSWindowRuleRegistry()
        if oos_window.oos_window_rule_id not in registry.REGISTERED_RULES:
            raise ValueError(
                f"OOS window rule '{oos_window.oos_window_rule_id}' is not registered. "
                "User/LLM-supplied OOS dates rejected."
            )
        
        # Validate data snapshot quality
        if data_snapshot.quality_status == "insufficient":
            raise ValueError(
                "Data snapshot quality is insufficient. Cannot freeze protocol with insufficient data."
            )
        
        # Validate universe quality
        if universe.quality_status == "insufficient":
            raise ValueError(
                "Universe quality is insufficient. Cannot freeze protocol with contaminated universe."
            )
        
        # Time consistency validation (P0-1: must integrate guard)
        guard = TimeConsistencyGuard()
        
        # Check universe snapshot time consistency
        universe_check = guard.validate_universe_snapshot(
            snapshot_date=universe.snapshot_date,
            backtest_start=backtest_start,
            universe_type=universe.universe_rule_type,
        )
        
        if universe_check.status == "fail":
            raise ValueError(
                f"Time consistency violation: {'; '.join(universe_check.blocking_violations)}"
            )
        
        # Check universe source type
        source_check = guard.validate_universe_source(
            source_type=universe.membership_source,
            source_snapshot_date=universe.snapshot_date,
            backtest_start=backtest_start,
        )
        
        if source_check.status == "fail":
            raise ValueError(
                f"Universe source violation: {'; '.join(source_check.blocking_violations)}"
            )
        
        # Compute shared_oos_window_id (deterministic)
        shared_oos_window_id = self._compute_shared_oos_window_id(
            oos_window.oos_window_rule_id,
            oos_window.oos_window_start,
            oos_window.oos_window_end,
        )
        
        # Generate protocol_snapshot_id
        protocol_snapshot_id = self._generate_protocol_snapshot_id(
            strategy_draft.strategy_revision_id,
            data_snapshot.data_snapshot_id,
        )
        
        # Freeze protocol snapshot
        return ResearchProtocolSnapshot(
            protocol_snapshot_id=protocol_snapshot_id,
            theme_id=strategy_draft.theme_id,
            hypothesis_source_snapshot_id=strategy_draft.hypothesis_source_snapshot_id,
            strategy_revision_id=strategy_draft.strategy_revision_id,
            sample_split_rule_id=strategy_draft.sample_split_rule_id,
            oos_window_rule_id=oos_window.oos_window_rule_id,
            oos_window_rule_params_json="{}",  # V1: no params
            oos_window_start=oos_window.oos_window_start,
            oos_window_end=oos_window.oos_window_end,
            shared_oos_window_id=shared_oos_window_id,
            backtest_universe_spec_id=strategy_draft.backtest_universe_spec_id,
            data_snapshot_id=data_snapshot.data_snapshot_id,
            kill_criteria_snapshot_id="",  # V1: not implemented
            prototype_gate_thresholds_json="{}",  # V1: placeholder
            strategy_config_hash=strategy_config_hash,
            data_snapshot_hash=data_snapshot.data_snapshot_hash,
            gate_criteria_hash=gate_criteria_hash,
            frozen_at=datetime.now(),
            frozen_by=frozen_by,
        )
    
    def _compute_config_hash(self, config_json: str) -> str:
        """Compute hash from strategy config JSON."""
        return hashlib.sha256(config_json.encode("utf-8")).hexdigest()
    
    def _compute_shared_oos_window_id(
        self,
        rule_id: str,
        oos_start: __import__("datetime").date,
        oos_end: __import__("datetime").date,
    ) -> str:
        """Compute deterministic shared_oos_window_id."""
        fingerprint = {
            "rule_id": rule_id,
            "oos_start": str(oos_start),
            "oos_end": str(oos_end),
        }
        serialized = json.dumps(fingerprint, sort_keys=True)
        return hashlib.sha256(serialized.encode("utf-8")).hexdigest()[:16]
    
    def _generate_protocol_snapshot_id(
        self,
        strategy_revision_id: str,
        data_snapshot_id: str,
    ) -> str:
        """Generate protocol_snapshot_id from inputs."""
        return f"protocol_{strategy_revision_id}_{data_snapshot_id}"
