"""
Signal Board REST API

FastAPI endpoints for Signal Board operations.

Endpoints:
    GET  /api/signals              - List signals (with filters)
    GET  /api/signals/{signal_id}  - Get single signal
    POST /api/signals/{signal_id}/review - Update review status
    POST /api/signals/batch-review - Batch update review status
    GET  /api/signals/summary      - Summary statistics

Design Principles:
- Read-only except for review status updates
- No signal generation (signals are generated by script)
- No signal deletion (audit trail preservation)
- All operations are idempotent (safe to retry)
"""

from datetime import date
from typing import List, Optional

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from contracts.signal_board import (
    PlannedSignal,
    SignalReviewRequest,
    SignalBatchReviewRequest,
    SignalSummary
)
from backend.db.signal_board import SignalBoardDB


# Router instance (to be included in main FastAPI app)
router = APIRouter(prefix="/api/signals", tags=["signal_board"])

# Database instance (initialized by main app)
_db: Optional[SignalBoardDB] = None


def init_signal_board_api(db_path: str):
    """
    Initialize Signal Board API with database path.
    
    Must be called before any API requests.
    
    Args:
        db_path: Path to SQLite database file
    """
    global _db
    _db = SignalBoardDB(db_path)


def get_db() -> SignalBoardDB:
    """Get database instance (dependency injection helper)."""
    if _db is None:
        raise RuntimeError("Signal Board API not initialized. Call init_signal_board_api() first.")
    return _db


@router.get("/summary", response_model=SignalSummary)
def get_signal_summary(
    signal_date: str = Query(..., description="Signal generation date (ISO format YYYY-MM-DD)")
):
    """
    Get summary statistics for signals on a given date.
    
    Args:
        signal_date: Date when signals were generated (ISO format)
    
    Returns:
        SignalSummary with counts by status and direction
    
    Examples:
        GET /api/signals/summary?signal_date=2023-12-29
    """
    db = get_db()
    
    signal_date_parsed = date.fromisoformat(signal_date)
    summary = db.get_summary(signal_date_parsed)
    
    return summary


@router.get("/strategies", response_model=List[dict])
def list_strategies(
    include_missing_admission: bool = Query(False, description="Include strategies without valid admission metadata (audit/internal only)")
):
    """
    List all strategy_id + strategy_version combinations in the database.

    Returns list of strategies with signal counts and latest signal date.
    Used by frontend to populate strategy selector.
    
    By default, only returns strategies with valid admission metadata
    (lifecycle_state_at_generation='prototype_passed').

    Returns:
        List of dicts with:
        - strategy_id: str
        - strategy_version: str
        - signal_count: int
        - latest_signal_date: str (ISO format)

    Example Response:
        [
            {
                "strategy_id": "momentum_v2",
                "strategy_version": "v2.1.0",
                "signal_count": 15,
                "latest_signal_date": "2023-12-29"
            },
            {
                "strategy_id": "mean_reversion",
                "strategy_version": "v1.0.0",
                "signal_count": 8,
                "latest_signal_date": "2023-12-28"
            }
        ]

    Examples:
        GET /api/signals/strategies
        GET /api/signals/strategies?include_missing_admission=true (audit mode)
    """
    db = get_db()
    strategies = db.list_strategies(include_missing_admission=include_missing_admission)
    return strategies


class SignalListResponse(BaseModel):
    """Paginated response for signal list queries."""
    items: List[PlannedSignal]
    total: int
    limit: int
    offset: int
    has_more: bool


@router.get("", response_model=SignalListResponse)
def list_signals(
    signal_date: Optional[str] = Query(None, description="Filter by signal generation date (ISO format YYYY-MM-DD)"),
    intended_execution_date: Optional[str] = Query(None, description="Filter by intended execution date (ISO format)"),
    status: Optional[str] = Query(None, description="Filter by review status (pending/ignored/watching/expired)"),
    direction: Optional[str] = Query(None, description="Filter by direction (buy/sell)"),
    snapshot_hash: Optional[str] = Query(None, description="Filter by snapshot hash"),
    strategy_id: Optional[str] = Query(None, description="Filter by strategy ID (M4.1 Phase 3)"),
    strategy_version: Optional[str] = Query(None, description="Filter by strategy version (M4.1 Phase 3)"),
    limit: int = Query(100, description="Max results to return"),
    offset: int = Query(0, description="Pagination offset"),
    include_missing_admission: bool = Query(False, description="Include signals without valid admission metadata (audit/internal only)")
):
    """
    List signals with optional filters.
    
    Default: returns most recent 100 signals (any date, any status).
    
    Examples:
        GET /api/signals?status=pending&limit=50
        GET /api/signals?signal_date=2023-12-29&direction=buy
        GET /api/signals?intended_execution_date=2024-01-02
        GET /api/signals?strategy_id=momentum_v2&strategy_version=v2.1.0
    """
    db = get_db()

    if limit <= 0 or limit > 500:
        raise HTTPException(status_code=400, detail="limit must be between 1 and 500")
    if offset < 0:
        raise HTTPException(status_code=400, detail="offset must be greater than or equal to 0")
    
    try:
        signal_date_parsed = date.fromisoformat(signal_date) if signal_date else None
        intended_execution_date_parsed = date.fromisoformat(intended_execution_date) if intended_execution_date else None
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="Invalid date format. Use YYYY-MM-DD.") from exc
    
    result = db.list_signals(
        signal_date=signal_date_parsed,
        intended_execution_date=intended_execution_date_parsed,
        review_status=status,
        direction=direction,
        snapshot_hash=snapshot_hash,
        strategy_id=strategy_id,
        strategy_version=strategy_version,
        limit=limit,
        offset=offset,
        include_missing_admission=include_missing_admission,
    )
    
    return result.to_dict()


@router.get("/{signal_id}", response_model=PlannedSignal)
def get_signal(signal_id: str):
    """
    Get a single signal by ID.
    
    Args:
        signal_id: Signal UUID
    
    Returns:
        PlannedSignal
    
    Raises:
        404: Signal not found
    """
    db = get_db()
    signal = db.get_signal(signal_id)
    
    if signal is None:
        raise HTTPException(status_code=404, detail=f"Signal {signal_id} not found")
    
    return signal


@router.post("/{signal_id}/review", response_model=PlannedSignal)
def review_signal(signal_id: str, request: SignalReviewRequest):
    """
    Update review status of a signal.
    
    Args:
        signal_id: Signal UUID
        request: Review request (status, reviewed_by, optional rejection_reason)
    
    Returns:
        Updated PlannedSignal
    
    Raises:
        404: Signal not found
        400: Invalid review status transition or missing rejection_reason
    
    Examples:
        POST /api/signals/{id}/review
        {
            "review_status": "watching",
            "reviewed_by": "trader1"
        }
        
        POST /api/signals/{id}/review
        {
            "review_status": "ignored",
            "reviewed_by": "trader1",
            "rejection_reason": "Low liquidity"
        }
    """
    db = get_db()
    
    # Validate: rejection_reason required if status is 'ignored'
    if request.review_status == "ignored" and not request.rejection_reason:
        raise HTTPException(
            status_code=400,
            detail="rejection_reason is required when review_status is 'ignored'"
        )
    
    # Update review status
    updated = db.update_review_status(
        signal_id=signal_id,
        review_status=request.review_status,
        reviewed_by=request.reviewed_by,
        rejection_reason=request.rejection_reason
    )
    
    if not updated:
        raise HTTPException(status_code=404, detail=f"Signal {signal_id} not found")
    
    # Return updated signal
    signal = db.get_signal(signal_id)
    return signal


class BatchReviewResponse(BaseModel):
    """Response for batch review operation."""
    updated_count: int
    signal_ids: List[str]


@router.post("/batch-review", response_model=BatchReviewResponse)
def batch_review_signals(request: SignalBatchReviewRequest):
    """
    Batch update review status of multiple signals.
    
    Args:
        request: Batch review request (signal_ids, status, reviewed_by, optional rejection_reason)
    
    Returns:
        BatchReviewResponse with count of updated signals
    
    Raises:
        400: Invalid review status or missing rejection_reason
    
    Examples:
        POST /api/signals/batch-review
        {
            "signal_ids": ["uuid1", "uuid2", "uuid3"],
            "review_status": "ignored",
            "reviewed_by": "trader1",
            "rejection_reason": "End of day, no time to review"
        }
    """
    db = get_db()
    
    # Validate: rejection_reason required if status is 'ignored'
    if request.review_status == "ignored" and not request.rejection_reason:
        raise HTTPException(
            status_code=400,
            detail="rejection_reason is required when review_status is 'ignored'"
        )
    
    # Batch update
    updated_count = db.batch_update_review_status(
        signal_ids=request.signal_ids,
        review_status=request.review_status,
        reviewed_by=request.reviewed_by,
        rejection_reason=request.rejection_reason
    )
    
    return BatchReviewResponse(
        updated_count=updated_count,
        signal_ids=request.signal_ids
    )
